### PR TITLE
docs(clone):update selector error

### PR DESCRIPTION
**Pull request by ajiho**
image

After update

image

By the way, I ignored the temporary file in the vscode editor`. vscode`

### CODE REVIEW

**Comment by franciscop** [comment]
Good catch and thank you for the PR, those are the generated files though, could you please add the fix here?

https://github.com/franciscop/umbrella/blob/master/src/plugins/clone/readme.md

**Comment by ajiho** [comment]
@franciscop Of course, please wait for me for a moment

**Comment by ajiho** [comment]
@franciscop done

**Comment by franciscop** [comment]
Awesome, thanks!

**Pull request merged**
