### PR TITLE
A .val() function/plugin

### PR DESCRIPTION
**Pull request by ProgramistaZpolski**
_This is my first time contributing to open source, so please notify me if I'm doing something wrong._

I added a .val(); function/plugin that allows to get the value of \<input\>s. 

I tried building a Todo App with UmbrellaJS and noticed that it didn't have a function to get values of inputs, so i created one myself.

I based this plugin on .text(), here's how to use it:
```js
// GET
u("#myInput").val();
// SET
u("#myInput").val("Hello World!");
```

### CODE REVIEW

**Comment by justingolden21** [comment]
Slightly off-topic, but speaking of useful functions to add, would we need something like [`prop`](https://api.jquery.com/prop/) from jQuery?

The [umbrella docs](https://umbrellajs.com/documentation#attr) mention to check the difference between attr and prop, but umbrella only seems to have attr. I'm trying to toggle the `disabled` attribute of inputs and it doesn't seem to work with umbrella's `attr` and umbrella doesn't have a `prop`; should it have one?

Relevant discussion for `disabled` and in jQuery and prop vs attr: https://www.drupal.org/project/tribune/issues/2033817#:~:text=To%20retrieve%20and%20change%20DOM,first%20message%20has%20been%20sent.

**Comment by ProgramistaZpolski** [comment]
> Slightly off-topic, but speaking of useful functions to add, would we need something like [`prop`](https://api.jquery.com/prop/) from jQuery?
> 
> The [umbrella docs](https://umbrellajs.com/documentation#attr) mention to check the difference between attr and prop, but umbrella only seems to have attr. I'm trying to toggle the `disabled` attribute of inputs and it doesn't seem to work with umbrella's `attr` and umbrella doesn't have a `prop`; should it have one?
> 
> Relevant discussion for `disabled` and in jQuery and prop vs attr: https://www.drupal.org/project/tribune/issues/2033817#:~:text=To%20retrieve%20and%20change%20DOM,first%20message%20has%20been%20sent.

Adding a .prop() function would be an excellent idea. I created an implementation of a `prop` function, and it only takes 13 lines of code, so I don't see a reason not to add this into the library.

For now, this code can polyfill the missing functionality:
```js
u.prototype.prop = function (propName, value) {
	if (value === undefined) {
		return this.first()[propName];
	};

	return this.each(function (node) {
		if (value === true) {
			node.setAttribute(propName, true);
		} else {
			node.removeAttribute(propName);
		};
	});
};
```

**Comment by franciscop** [comment]
Hi @ProgramistaZpolski, thanks for the PR. I made UmbrellaJS to help with JS when using raw Javascript was difficult, but I think in the case of `.val()` the native Javascript is practically the same as adding a custom method. Adding a custom method has a cost, it means people need to learn a new way of doing things instead of rely on the universal Javascript, so in these cases it's discouraged.

What do I mean by this? In practical situations, these are the same:

```js
// With .val()
u("#myInput").val();
u("#myInput").val("Hello World!");

// Without .val()
u("#myInput").first().value;
u("#myInput").first().value = "Hello World!";
```

When reading the value, you only care about the first one so it's okay. In the past, for `.text()` and `.html()` we have done the method because when writing the value, you might want to write multiple nodes at once or don't care if there's no match (for example adding an icon to all items on a list).

However, in the case of input, I believe writing a value to an input is a much more individual operation, and in the vast majority of cases you'll be writing to a single input value. If there is none, it's probably a bug in the code and we don't want to ignore it. And writing to multiple inputs at once in JS is very rare (and can still be done, it just takes 2 more lines, which is fine). The only case I can think this would be widely useful is resetting a form, but in that case you are better off with the native `form.reset()` anyway.

That is why I didn't write a `.val()` function initially with Umbrella JS and why I believe it should not have one. @justingolden21 same thing about `.prop()`, I think the question is kind of in-topic here because both are very similar in that the argument why I believe should not be included is the same.

> "and it only takes 13 lines of code, so I don't see a reason not to add this into the library"

That is true in this case, but then you can use the same argument 20-30 times more with other method and then it _does_ become a lot of code. So the line has to be drawn somewhere, and I decided it was "when the benefit of using the method significantly outweighs the cost of learning it in the most common situations". This is a pretty low bar IMHO! But e.g. if the user already knows how to use the method (because of jQuery!) then I consider the cost to be a lot lower, so preference is given to jQuery-like methods. And in this case, even if the cost is low, the benefit is also low as explained.

I'm open to be convinced otherwise, but I've also put a lot of thought on this before and done a lot of searches about typical patterns which led me to this conclusion. I'll leave the issue open for a bit.

BTW, Umbrella is made on purpose to be very easily extensible. If anyone really wants a method that is not part of the library, you can create a `methods.js` file or similar and put these onto it:

```js
// Set or get value of input elements
u.prototype.val = function (value) {
  // If no value is passed just return the value of the element
  if (value === undefined) {
    return this.first().value;
  }

  return this.each(function (node) {
    // Set the value to the element
    node.value = value;
  });
};

u.prototype.prop = function (propName, value) {
  if (value === undefined) {
    return this.first()[propName];
  };

  return this.each(function (node) {
    if (value === true) {
      // Is this correct? Or do you want "node[propName] = true;"?
      node.setAttribute(propName, true);
    } else {
      node.removeAttribute(propName);
    };
  });
};
```

Then import it as usual, adding this file between umbrella and your code:

```html
<script src="https://cdn.jsdelivr.net/npm/umbrellajs"></script>
<script src="/methods.js"></script>
<script src="/mycode.js"></script>
```

**Comment by justingolden21** [comment]
Thank you for explaining why in a detailed manner before closing, as well as providing the solution with val (`u("#myInput").first().value`) and mentioning that it's easy to extend (didn't think of that, figured if I wanted a feature someone else had I'd be giving up future updates and bug fixed)

Idea/suggestion: a repo for "umbrella prime" or something (or even a file in this repo) that has the extended features commonly asked for such as `val` which (as you pointed out) take time to learn and take up space in umbrella / go against design philosophy, but someone who wants them doesn't just have to go to jQuery or an alternative, they can still use umbrella, just with the "full" / "extended" feature set

**Comment by franciscop** [comment]
Thanks for the suggestion, initially Umbrella JS was something like that. IIRC there was a `core` and then events and AJAX were not part of it, but at some point AJAX was deprecated for the native `fetch()` and events were made part of the core, unifying the library.

I don't think there's much value in the few methods that people want being part of a separated library because as I showed, `.val()`'s native alternative is normally not a burden to use. But that's my opinion of course, you are free to create `umbrella extended` or similar with these methods.

**Comment by justingolden21** [comment]
Thanks for the info. Yeah, I think that `umbrella extended` at just 2-3 more kb would certainly be something many devs would want, but it would also not belong in the base umbrella as it adds little value and increases the file size. It may even *save* time because it would stop people from asking about `val` and similar 😄

**Pull request closed without merging**
