### PR TITLE
Added .css() method

### PR DESCRIPTION
**Pull request by mesbahulalam**
A .css() method to get or set css properties of or to element(s). While getting a value, just pass the property name. It will return the computed style for the given property for the first matched element. When setting a property, give it a property and a value argument. It will set them for all the matched elements.

### CODE REVIEW

**Comment by franciscop** [comment]
Thanks for the PR, but this is not something that I'd like to see added to Umbrella JS. Related PR here:
https://github.com/franciscop/umbrella/pull/88

**Comment by leeoniya** [comment]
@franciscop the reasoning given in #88 doesn't really address a lot of cases.

if you wanted to compute a color scale value, for example, it is not possible to create classes for all possible values along it. another example is if you need to set css `transform/translate` on drag/drop, you cannot handle this with a class. there are dozens of other use-cases when something like this is useful.

as much as purists want to de-couple JS and CSS, clearly it's not always possible, and not always the right direction, just like React's dom/html management is a better solution for complex SPAs than a bunch of vanilla js or jQuery code written on top of static & cloned html `<template>` elements.

since this PR is neither complex, nor a lot of code, i think it's definitely worth considering.

/$0.02

**Comment by justingolden21** [comment]
I personally think this would be an awesome addition, and the only reason not to would be if the file size was increased significantly. I wouldn't want umbrella to have to get significantly larger for this, that's all. But I think it's extremely useful, especially if you're trying to grab the market of former jQuery programmers 😄 

Use case:

I currently am finding myself trying to set the stroke color of a SVG with JS dynamically:

former jQuery code:
`$('#mypath').css('stroke', 'rgb(99, 102, 241)');`

current umbrellaJS code:
`u('#mypath').css('stroke', 'rgb(99, 102, 241)');`
but without a `css` method this doesn't work, and I cannot just do this with the `.style.stroke` property as one would think with vanilla JS, and I cannot just make a class for it since this value is dynamic.

**Comment by justingolden21** [comment]
Also, when I want to style multiple elements, instead of just setting it in the jQuery/umbrella way:

`u('#diagram path[id]').style.stroke = '';`

I have to loop through with `each` and then use vanilla inside the loop... Ick

```js
u('#diagram path[id]').each( (elm, idx)=> {
	elm.style.stroke = '';
});
```

**Pull request closed without merging**
