### PR TITLE
Add nth selector

### PR DESCRIPTION
**Pull request by jrmd**
Added an nth selector, it works exactly like `first()` and `last()` but you can grab any elements index
I also added .idea to git ignore since i use intellij and it auto creates this folder.

### CODE REVIEW

**Comment by gnadelwartz** [comment]
as Im porting from jQuery and umbrella use a very similar syntax we should consider naming it `.eq()` as in jQuery to stay with the similarity. [see documentation](https://api.jquery.com/eq/)

additionally jQuery index starts with 0, if we implent it this way so we save one increment and it's identical to umbrella nodes[n] syntax.

**Comment by gnadelwartz** [comment]
```
// Get the nth of the nodes
u.prototype.eq = function (index) {
  return this.nodes[index||0] || [];
}
```

**Comment by franciscop** [comment]
I agree, I think it should start by index 0. We are working with Javascript after all, leave the 1-index for CSS.

**Comment by franciscop** [comment]
But still, I am closing this since it is virtually the same as doing what you can do now natively:

```js
// Available now:
u('a').nodes[0];

// Proposed:
u('a').nth(0);
```

**Pull request closed without merging**
