### PR TITLE
empty.js with tests and docs

### PR DESCRIPTION
**Pull request by ubery**
Hello, it's my first time contributing to open source. It's simple method, but really useful. I've got another one but in second request.

### CODE REVIEW

**Comment by franciscop** [comment]
Hi @ubery , thank you for the contribution, I like empty.js. I haven't tested it (yet), but isn't the implemented method:

```js
u.prototype.empty = function () {
  return this.each(function (node) {
    while (node.firstChild) {
      node.removeChild(node.firstChild);
    }
  });
};
```

similar to doing this?

```js
u('.something').children().remove();
```

Or even this?

```js
u('.something > *').remove();
```

About contributing to open source, I highly recommend opening an issue before doing all the work for a PR as complete as yours since the devs of the library can normally give a lot of insight and/or tell whether it's a thing that fits within the library or not. Both of the PR are technically great, but the css.js one is not a good fit for Umbrella JS and this one might be or might not.

**Comment by franciscop** [comment]
Okay from the docs I see that `firstChild` returns any node type while `.children()` returns the HTML Elements, so `empty()` would also clean this:

```html
<div>Hello!</div>
```

While `u('div').children().remove()` would not. [Example showing it](https://jsfiddle.net/franciscop/fv2Lzwwa/). I'll accept this PR ASAP.

**Comment by ubery** [comment]
Thank You for your feedback. Completely understand your idea of this library. I made this code as a extensions to your library for one project. In my experience css method is useful primarily for read-only case, when need to compute something based on style.

**Comment by franciscop** [comment]
When I merge this I will test to see if this produces the same result (it seems like it does):

```js
u.prototype.empty = function(){
  return this.html('');
}
```

**Comment by ubery** [comment]
I've tested this also, but it's far slowest than removing by firstChild.

**Comment by franciscop** [comment]
Really? I would expect it totally depends on the usecase. However, as empty() looks it's probably not going to be in a hot path such as `.each()`, `.map()`, `.args()` and the like, a 10x or even 100x slowdown would be totally acceptable. How did you use this function?

**Comment by ubery** [comment]
https://jsperf.com/innerhtml-vs-removechild

**Comment by franciscop** [comment]
Oh I am not arguing with which one is faster. I am arguing that it doesn't really matter; If you really need to empty 1 millon of elements/second something is very wrong. Heck, even 1k ops/second would still be totally acceptable.

User threshold to notice something like this is 0.1s. Let's be conservative and say 0.01s and let's add a smartphone instead of a laptop so another 10x of slowdown (I have a low-power laptop already), so it becomes a 0.001 slowdown. If someone needs to empty 1.000 elements/second (in this super-contrieved situation) I am sure that they have bigger things to worry about.

My point: speed is not a factor here at all. Umbrella JS already surpases jQuery in many regards for speed with the simple fact that the API is really simple, while jQuery was designed (spending many thousands of man-hours) for some speed optimizations for browsers that are constantly changing and now play against it. So the rule of thumb has been to keep it simple and reuse methods internally and that's why I suggest using `.html('')` instead of adding another way of doing something that can already be done internally.

**Comment by ubery** [comment]
And I'm happy with this, simplicity and reusability is what I like in your library.

**Comment by franciscop** [comment]
Here it is, released: https://umbrellajs.com/documentation#empty

The CDN takes few minutes, but it will be in https://unpkg.com/umbrellajs@2.7 soon

**Comment by franciscop** [comment]
Oh and thank you for the contributions!

**Comment by ubery** [comment]
Thank You, I have some idea (and even a bit of code, used in my project as I said), but I will open new issue when come back to home.

**Pull request merged**
