### PR TITLE
Supporting ES Module

### PR DESCRIPTION
**Pull request by asciian**
Hello @franciscop . 

Now we can use ES Module feature on the almost browsers.
I added a line to support ES Module.

Thank you.

### CODE REVIEW

**Comment by franciscop** [comment]
Hi @asciian, thanks for the pull request. However, how is that different from the paragraph just above?

```js
## Module support

If you use a front-end module bundler like Webpack or Browserify, `u` and `ajax` are exposed as CommonJS exports. You can pull them in like so:

var u = require('path/to/umbrella').u;
// or ES-style modules
import { u } from 'path/to/umbrella';
```

Umbrella is already working with ES6, I just tested it installing it fresh on a create-react-app project and doing:

```js
import { u } from 'umbrellajs';

console.log(u('title').html());
```

It correctly logged the title. So it seems we do not need the extra file, and the description was already there. Am I missing something? Thanks

**Comment by asciian** [comment]
The difference is being able to use the umbrella as modules without any compilers and bundlers.
As you know, usage of umbrella are two ways. One is using as global variables like the following;

```html
<script src="./umbrella.js"></script>
<!-- Now we can use u everywhere! -->
<script>
console.log(u('title').html());
</script>
```
Another is using as local variable with some bundlers like webpack;

```js
import { u } from 'umbrellajs';

console.log(u('title').html());
```

So create-react-app using webpack and babel-loader, they compile ES6 script to ES5 script which has no module syntax like `require()`.

In past days we need to use them if we want to use module syntax but in these days almost browsers supports module syntax we call ES6 modules, so we don't need to use them.

Actually you can see this file directly with google chrome;

```html
<html>
<head>
<title>test</title>
<script type="module">
import { u } from "./umbrella.esm.js"; // don't use "./umbrella.js" because it will be failed.
console.log(u('title').html());
</script>
</head>
<body>
<body>
</html>
```

For more information about ES6 modules in the browser, Please see this page.

https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/

**Comment by franciscop** [comment]
@asciian I see, this makes some sense. However to integrate it it'd have to be integrated with the current build tool (Grunt), otherwise it could get out of sync with the main code. Does UMD work with this case though? [Universal Module Definition](https://github.com/umdjs/umd)

**Comment by asciian** [comment]
UMD hasn't supported ES6 Module yet suddenly because ES6 Module uses `export` as a **keyword**, not as a special object like `exports` in Node thus there is no way to use `export` avoiding a syntax error. However, Vue.js split files, like this request, to support this feature. To work with UMD, I recommend generating two files separately. If I found a way to generate with grunt, I commit to this request.

**Comment by franciscop** [comment]
I thought so but wasn't 100% sure. With grunt you can also run scripts, it doesn't need to be an actual grunt plugin doing this. A script concatenating the `export { u, ajax }` I think would also work well.

**Comment by asciian** [comment]
Yes. I agree your idea, At first of this request, I just concatenating the `export { u, ajax}` with own hand.
If you know to concatenate it automatically with grunt, please do that.

**Comment by franciscop** [comment]
Shouldn't it be the `.mjs` extension?

**Comment by asciian** [comment]
I agree with what you would like. However, All editor supports `esm.js` because filename ends with `js`.

**Comment by franciscop** [comment]
Bumped, should be available on `3.1.0`. However, it's `import u from 'umbrellajs/umbrella.esm.js';`

**Comment by franciscop** [comment]
Updated docs to reflect that, thanks for the PR! :+1:

**Pull request merged**
