### PR TITLE
Add resize function to create a event listener on window

### PR DESCRIPTION
**Pull request by jrmd**
Since ```u(window).on('resize', callback)``` doesnt work I added this function.

### CODE REVIEW

**Comment by franciscop** [comment]
Wait, why doesn't `u(window).on('resize', callback);` work? It should work, otherwise that shou bug.

**Comment by franciscop** [comment]
This works:

```js
u([window]).on('resize', function(){
   ...
});
```

With the extra `[]` on the selector. Right now single element only allows for `nodeName` as seen in https://github.com/franciscop/umbrella/blob/master/src/umbrella.js#L29; another check should be added for window:

```js
 if (parameter && (parameter.nodeName || parameter === window)) {
  ...
}
```

**Comment by jrmd** [comment]
Could be that the 'on' targets all nodes in a list but since window isn't a node it isn't added :)

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by franciscop** [comment]
@jrmd yes, added a comment seconds before yours (notifying in case you miss it since they were so close).

**Comment by jrmd** [comment]
Ahh that makes sense, then there is no need for my pull request :)

Glad there is an easy solution, great job on the library btw! 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request closed without merging**
