### PR TITLE
Added TypeScript declarations

### PR DESCRIPTION
**Pull request by Simon-Tang**
I was looking into using Umbrella in a TypeScript project, so I decided to get familiar with the API by writing out TypeScript declarations for the library. I tried my best to capture the method signatures accurately, and I've tested out a few of the methods in my editor (attr, append, children, addClass) but I would really say you might be the only definitive person who could confirm that the whole file makes sense.

I've tried applying the examples from the documentation page and was able to get them to pass the TypeScript validator, with only a few minor tweaks (e.g. casting values as non-null/non-false/`HTMLFormElement`)

I hope this would be of interest, let me know what you think.

Usage:

```
import u from 'umbrellajs';
import type { Umbrella } from 'umbrellajs';

function myFunction(): Umbrella {
  return u();
}

// https://www.typescriptlang.org/docs/handbook/2/functions.html#declaring-this-in-a-function
const callback = function (this: Umbrella) {
  new u(this);
};

u().off('event1', 'selector', callback);
```

### CODE REVIEW

**Comment by Simon-Tang** [comment]
Re: `event.detail`, we could consider something like this:

We could have a snippet roughly like `details = (event.detail && event.detail._umbrella) || []`, which would give us either an empty array or the `event.detail._umbrella` array if present.

In the `trigger()` function, we could do: `var opts = { bubbles: true, cancelable: true, detail: { _umbrella: data } };`

And when we check for Umbrella args:

```
  var callback = function (e) {
    return cb.apply(this, [e].concat(e.detail && e.detail._umbrella || []));
  };
```

**Comment by franciscop** [comment]
I literally searched last time one of my projects had a PR adding `index.d.ts` and couldn't find anything reasonable, but it seems like now https://github.com/ai/check-dts might just be it! I'll test it first in one of my smaller projects and see how it goes.

**Comment by cies** [comment]
I was looking for a better jQuery with TS types available. jQuery alternatives do not currently provide their own `.d.ts` files yet, this project might be the first. Umbrella is also the only jQuery alternative that is actively developed.

I'm still deciding if we should use any "progressive enhancement" library, or simply use vanilla JS with TS and `dom.d.ts`.

**Comment by franciscop** [comment]
Oh totally forgot, but yeah I tested `check-dts` into [another project of mine](https://github.com/franciscop/translate) and loved the experience! Basically you write index.d.ts as you did (or umbrella.d.ts in this case), and then a `index.types.ts` or similar with tests for the types.

I am happy to merge this for now, but for publishing it officially we'd need:

- [ ] Fix the event.detail type; at this point I don't think it's a good idea to change it or how it works.
- [ ] Add the dev dependency `check-dts`.
- [ ] Add a [`tsconfig.json` like here](https://github.com/franciscop/translate/blob/master/tsconfig.json) (not totally sure if needed, 100% happy to be proven wrong).
- [ ] Add some basic testing for the types like [`index.d.ts`](https://github.com/franciscop/translate/blob/master/index.d.ts).

I am a bit busy at the moment to be investing too much time here, but around summer I should have more time to work on it. If anyone wants to send PRs with the details above happy to merge to speed things up!

**Comment by franciscop** [comment]
> Umbrella is also the only jQuery alternative that is actively developed.

I would say "it's actively maintained" BTW, no major changes are expected at the API.

**Comment by franciscop** [comment]
> I'm still deciding if we should use any "progressive enhancement" library, or simply use vanilla JS with TS and dom.d.ts.

Don't want to self-sabotage, but what I usually do and would recommend: for a tiny project, start with vanilla JS. If it grows enough or you find yourself repeating a lot of `document.querySelectorAll()` etc, then throw UmbrellaJS in there. I see it usually under 100-200 LoC (JS) normally it might not be needed, over 200 of lines of raw JS I'd start to recommend using Umbrella.

**Comment by Simon-Tang** [comment]
Happy to see it merged, glad that I could contribute. I agree that we should have some more robust coverage before publishing the types for public use. The `check-dts` tool looks very cool! It's not my area of familiarity either but I think you have the right idea with the `tsconfig.json` as well.

`event.detail` certainly should be treated as a totally separate matter (if at all), agreed. The reason it came up for me was that handling a `click` event resulted in the extra mouse button int parameter being present as a callback argument at runtime (since click events have their event.detail populated). But for the purposes of just defining TypeScript signatures, this should be mostly fine in practice.

```ts
    on(
      events: string | string[],
      callback: (this: this, e: Event, ...data: any[]) => void
    ): this;
```

The only issue would be if some consumer code was using the contents of `data` in the callback without checking the event type first.

**Pull request merged**
